// Operadores Aritiméticos (matemáticos)
let salario = 100;
// +, -,*,**
console.log('Operadores aritiméticos');
console.log('soma salário 100 + 100 =');
console.log(salario + salario);
console.log('subitrair salário 100 - 100 =');
console.log(salario - salario);
console.log('dividir salário 100 / 100 =');
console.log(salario / salario);
console.log('multiplicar salário 100 * 100 =');
console.log(salario * salario);
console.log('pontêncialização de 2²=');
console.log(2** 2);